// © 2025 Sharon Aicler (saichler@gmail.com)
//
// Layer 8 Ecosystem is licensed under the Apache License, Version 2.0.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// l8agent.proto defines the types for the Layer 8 AI Agent shared library.
// These types are used by all Layer 8 projects that integrate the AI agent.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: l8agent.proto

package l8agent

import (
	l8api "github.com/saichler/l8types/go/types/l8api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type L8AgentConvoStatus int32

const (
	L8AgentConvoStatus_L8_AGENT_CONVO_STATUS_UNSPECIFIED L8AgentConvoStatus = 0
	L8AgentConvoStatus_L8_AGENT_CONVO_STATUS_ACTIVE      L8AgentConvoStatus = 1
	L8AgentConvoStatus_L8_AGENT_CONVO_STATUS_ARCHIVED    L8AgentConvoStatus = 2
)

// Enum value maps for L8AgentConvoStatus.
var (
	L8AgentConvoStatus_name = map[int32]string{
		0: "L8_AGENT_CONVO_STATUS_UNSPECIFIED",
		1: "L8_AGENT_CONVO_STATUS_ACTIVE",
		2: "L8_AGENT_CONVO_STATUS_ARCHIVED",
	}
	L8AgentConvoStatus_value = map[string]int32{
		"L8_AGENT_CONVO_STATUS_UNSPECIFIED": 0,
		"L8_AGENT_CONVO_STATUS_ACTIVE":      1,
		"L8_AGENT_CONVO_STATUS_ARCHIVED":    2,
	}
)

func (x L8AgentConvoStatus) Enum() *L8AgentConvoStatus {
	p := new(L8AgentConvoStatus)
	*p = x
	return p
}

func (x L8AgentConvoStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (L8AgentConvoStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_l8agent_proto_enumTypes[0].Descriptor()
}

func (L8AgentConvoStatus) Type() protoreflect.EnumType {
	return &file_l8agent_proto_enumTypes[0]
}

func (x L8AgentConvoStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use L8AgentConvoStatus.Descriptor instead.
func (L8AgentConvoStatus) EnumDescriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{0}
}

type L8AgentPromptCategory int32

const (
	L8AgentPromptCategory_L8_AGENT_PROMPT_CATEGORY_UNSPECIFIED L8AgentPromptCategory = 0
	L8AgentPromptCategory_L8_AGENT_PROMPT_CATEGORY_GENERAL     L8AgentPromptCategory = 1
	L8AgentPromptCategory_L8_AGENT_PROMPT_CATEGORY_REPORTING   L8AgentPromptCategory = 2
	L8AgentPromptCategory_L8_AGENT_PROMPT_CATEGORY_WORKFLOW    L8AgentPromptCategory = 3
	L8AgentPromptCategory_L8_AGENT_PROMPT_CATEGORY_ANALYSIS    L8AgentPromptCategory = 4
)

// Enum value maps for L8AgentPromptCategory.
var (
	L8AgentPromptCategory_name = map[int32]string{
		0: "L8_AGENT_PROMPT_CATEGORY_UNSPECIFIED",
		1: "L8_AGENT_PROMPT_CATEGORY_GENERAL",
		2: "L8_AGENT_PROMPT_CATEGORY_REPORTING",
		3: "L8_AGENT_PROMPT_CATEGORY_WORKFLOW",
		4: "L8_AGENT_PROMPT_CATEGORY_ANALYSIS",
	}
	L8AgentPromptCategory_value = map[string]int32{
		"L8_AGENT_PROMPT_CATEGORY_UNSPECIFIED": 0,
		"L8_AGENT_PROMPT_CATEGORY_GENERAL":     1,
		"L8_AGENT_PROMPT_CATEGORY_REPORTING":   2,
		"L8_AGENT_PROMPT_CATEGORY_WORKFLOW":    3,
		"L8_AGENT_PROMPT_CATEGORY_ANALYSIS":    4,
	}
)

func (x L8AgentPromptCategory) Enum() *L8AgentPromptCategory {
	p := new(L8AgentPromptCategory)
	*p = x
	return p
}

func (x L8AgentPromptCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (L8AgentPromptCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_l8agent_proto_enumTypes[1].Descriptor()
}

func (L8AgentPromptCategory) Type() protoreflect.EnumType {
	return &file_l8agent_proto_enumTypes[1]
}

func (x L8AgentPromptCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use L8AgentPromptCategory.Descriptor instead.
func (L8AgentPromptCategory) EnumDescriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{1}
}

type L8AgentPromptStatus int32

const (
	L8AgentPromptStatus_L8_AGENT_PROMPT_STATUS_UNSPECIFIED L8AgentPromptStatus = 0
	L8AgentPromptStatus_L8_AGENT_PROMPT_STATUS_ACTIVE      L8AgentPromptStatus = 1
	L8AgentPromptStatus_L8_AGENT_PROMPT_STATUS_INACTIVE    L8AgentPromptStatus = 2
)

// Enum value maps for L8AgentPromptStatus.
var (
	L8AgentPromptStatus_name = map[int32]string{
		0: "L8_AGENT_PROMPT_STATUS_UNSPECIFIED",
		1: "L8_AGENT_PROMPT_STATUS_ACTIVE",
		2: "L8_AGENT_PROMPT_STATUS_INACTIVE",
	}
	L8AgentPromptStatus_value = map[string]int32{
		"L8_AGENT_PROMPT_STATUS_UNSPECIFIED": 0,
		"L8_AGENT_PROMPT_STATUS_ACTIVE":      1,
		"L8_AGENT_PROMPT_STATUS_INACTIVE":    2,
	}
)

func (x L8AgentPromptStatus) Enum() *L8AgentPromptStatus {
	p := new(L8AgentPromptStatus)
	*p = x
	return p
}

func (x L8AgentPromptStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (L8AgentPromptStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_l8agent_proto_enumTypes[2].Descriptor()
}

func (L8AgentPromptStatus) Type() protoreflect.EnumType {
	return &file_l8agent_proto_enumTypes[2]
}

func (x L8AgentPromptStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use L8AgentPromptStatus.Descriptor instead.
func (L8AgentPromptStatus) EnumDescriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{2}
}

// L8AgentConversation - Prime Object (metadata only, no messages)
// Stored by internal OrmService, not exposed via web API directly.
// Passes Prime Object test: independent lifecycle, queried directly.
type L8AgentConversation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title          string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Status         int32  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"` // L8AgentConvoStatus enum
	CreatedAt      int64  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *L8AgentConversation) Reset() {
	*x = L8AgentConversation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8AgentConversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8AgentConversation) ProtoMessage() {}

func (x *L8AgentConversation) ProtoReflect() protoreflect.Message {
	mi := &file_l8agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8AgentConversation.ProtoReflect.Descriptor instead.
func (*L8AgentConversation) Descriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{0}
}

func (x *L8AgentConversation) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *L8AgentConversation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *L8AgentConversation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *L8AgentConversation) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *L8AgentConversation) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *L8AgentConversation) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type L8AgentConversationList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*L8AgentConversation `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata *l8api.L8MetaData      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *L8AgentConversationList) Reset() {
	*x = L8AgentConversationList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8AgentConversationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8AgentConversationList) ProtoMessage() {}

func (x *L8AgentConversationList) ProtoReflect() protoreflect.Message {
	mi := &file_l8agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8AgentConversationList.ProtoReflect.Descriptor instead.
func (*L8AgentConversationList) Descriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{1}
}

func (x *L8AgentConversationList) GetList() []*L8AgentConversation {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *L8AgentConversationList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// L8AgentChatMessage - Prime Object
// Individual chat message, stored separately for efficiency.
// Stored by internal OrmService, not exposed via web API directly.
type L8AgentChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string   `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // FK to conversation
	Sequence       int32    `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`                                  // Order within conversation
	IsLlm          bool     `protobuf:"varint,3,opt,name=is_llm,json=isLlm,proto3" json:"is_llm,omitempty"`                           // true = assistant, false = user
	Message        string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                                     // Message content
	AllowedModules []string `protobuf:"bytes,5,rep,name=allowed_modules,json=allowedModules,proto3" json:"allowed_modules,omitempty"` // Modules context (for user messages)
	Timestamp      int64    `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TokenCount     int32    `protobuf:"varint,7,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"` // LLM token usage (for assistant messages)
}

func (x *L8AgentChatMessage) Reset() {
	*x = L8AgentChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8AgentChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8AgentChatMessage) ProtoMessage() {}

func (x *L8AgentChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_l8agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8AgentChatMessage.ProtoReflect.Descriptor instead.
func (*L8AgentChatMessage) Descriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{2}
}

func (x *L8AgentChatMessage) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *L8AgentChatMessage) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *L8AgentChatMessage) GetIsLlm() bool {
	if x != nil {
		return x.IsLlm
	}
	return false
}

func (x *L8AgentChatMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *L8AgentChatMessage) GetAllowedModules() []string {
	if x != nil {
		return x.AllowedModules
	}
	return nil
}

func (x *L8AgentChatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *L8AgentChatMessage) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

type L8AgentChatMessageList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*L8AgentChatMessage `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata *l8api.L8MetaData     `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *L8AgentChatMessageList) Reset() {
	*x = L8AgentChatMessageList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8AgentChatMessageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8AgentChatMessageList) ProtoMessage() {}

func (x *L8AgentChatMessageList) ProtoReflect() protoreflect.Message {
	mi := &file_l8agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8AgentChatMessageList.ProtoReflect.Descriptor instead.
func (*L8AgentChatMessageList) Descriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{3}
}

func (x *L8AgentChatMessageList) GetList() []*L8AgentChatMessage {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *L8AgentChatMessageList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// L8AgentChatConversation - Facade/pseudo model (NOT stored directly)
// Assembled by AgntChat facade service from L8AgentConversation + L8AgentChatMessage.
// This is the model exposed to the web API and UI.
type L8AgentChatConversation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string                `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title          string                `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Status         int32                 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"` // L8AgentConvoStatus enum
	Messages       []*L8AgentChatMessage `protobuf:"bytes,5,rep,name=messages,proto3" json:"messages,omitempty"`
	CreatedAt      int64                 `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64                 `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *L8AgentChatConversation) Reset() {
	*x = L8AgentChatConversation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8agent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8AgentChatConversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8AgentChatConversation) ProtoMessage() {}

func (x *L8AgentChatConversation) ProtoReflect() protoreflect.Message {
	mi := &file_l8agent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8AgentChatConversation.ProtoReflect.Descriptor instead.
func (*L8AgentChatConversation) Descriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{4}
}

func (x *L8AgentChatConversation) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *L8AgentChatConversation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *L8AgentChatConversation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *L8AgentChatConversation) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *L8AgentChatConversation) GetMessages() []*L8AgentChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *L8AgentChatConversation) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *L8AgentChatConversation) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type L8AgentChatConversationList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*L8AgentChatConversation `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata *l8api.L8MetaData          `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *L8AgentChatConversationList) Reset() {
	*x = L8AgentChatConversationList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8agent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8AgentChatConversationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8AgentChatConversationList) ProtoMessage() {}

func (x *L8AgentChatConversationList) ProtoReflect() protoreflect.Message {
	mi := &file_l8agent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8AgentChatConversationList.ProtoReflect.Descriptor instead.
func (*L8AgentChatConversationList) Descriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{5}
}

func (x *L8AgentChatConversationList) GetList() []*L8AgentChatConversation {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *L8AgentChatConversationList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// L8AgentPrompt - Prime Object
// Passes Prime Object test: independent lifecycle, queried across all users,
// reusable templates not tied to a single conversation
type L8AgentPrompt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PromptId       string   `protobuf:"bytes,1,opt,name=prompt_id,json=promptId,proto3" json:"prompt_id,omitempty"`
	Name           string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SystemPrompt   string   `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`       // The prompt template text
	Category       int32    `protobuf:"varint,5,opt,name=category,proto3" json:"category,omitempty"`                                  // L8AgentPromptCategory enum
	Status         int32    `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`                                      // L8AgentPromptStatus enum
	AllowedModules []string `protobuf:"bytes,7,rep,name=allowed_modules,json=allowedModules,proto3" json:"allowed_modules,omitempty"` // Module keys the prompt can access
	CreatedBy      string   `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
}

func (x *L8AgentPrompt) Reset() {
	*x = L8AgentPrompt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8agent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8AgentPrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8AgentPrompt) ProtoMessage() {}

func (x *L8AgentPrompt) ProtoReflect() protoreflect.Message {
	mi := &file_l8agent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8AgentPrompt.ProtoReflect.Descriptor instead.
func (*L8AgentPrompt) Descriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{6}
}

func (x *L8AgentPrompt) GetPromptId() string {
	if x != nil {
		return x.PromptId
	}
	return ""
}

func (x *L8AgentPrompt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *L8AgentPrompt) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *L8AgentPrompt) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *L8AgentPrompt) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *L8AgentPrompt) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *L8AgentPrompt) GetAllowedModules() []string {
	if x != nil {
		return x.AllowedModules
	}
	return nil
}

func (x *L8AgentPrompt) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type L8AgentPromptList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*L8AgentPrompt  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata *l8api.L8MetaData `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *L8AgentPromptList) Reset() {
	*x = L8AgentPromptList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8agent_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8AgentPromptList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8AgentPromptList) ProtoMessage() {}

func (x *L8AgentPromptList) ProtoReflect() protoreflect.Message {
	mi := &file_l8agent_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8AgentPromptList.ProtoReflect.Descriptor instead.
func (*L8AgentPromptList) Descriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{7}
}

func (x *L8AgentPromptList) GetList() []*L8AgentPrompt {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *L8AgentPromptList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_l8agent_proto protoreflect.FileDescriptor

var file_l8agent_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6c, 0x38, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6c, 0x38, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x1a, 0x0b, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc3, 0x01, 0x0a, 0x13, 0x4c, 0x38, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a,
	0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x7a, 0x0a, 0x17, 0x4c,
	0x38, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6c, 0x38, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4c,
	0x38, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x38, 0x61,
	0x70, 0x69, 0x2e, 0x4c, 0x38, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0xf2, 0x01, 0x0a, 0x12, 0x4c, 0x38, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x27,
	0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x6c, 0x6c, 0x6d, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x4c, 0x6c, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x61,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x78, 0x0a, 0x16,
	0x4c, 0x38, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x38, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4c,
	0x38, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x38, 0x61, 0x70,
	0x69, 0x2e, 0x4c, 0x38, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x80, 0x02, 0x0a, 0x17, 0x4c, 0x38, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x37, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x38, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4c,
	0x38, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x82, 0x01, 0x0a, 0x1b, 0x4c, 0x38,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6c, 0x38, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x4c, 0x38, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12,
	0x2d, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x4d, 0x65, 0x74, 0x61,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x83,
	0x02, 0x0a, 0x0d, 0x4c, 0x38, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x70, 0x72,
	0x6f, 0x6d, 0x70, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x27, 0x0a, 0x0f,
	0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18,
	0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x4d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x62, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x42, 0x79, 0x22, 0x6e, 0x0a, 0x11, 0x4c, 0x38, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x50,
	0x72, 0x6f, 0x6d, 0x70, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x38, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x4c, 0x38, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x52,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e,
	0x4c, 0x38, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x2a, 0x81, 0x01, 0x0a, 0x12, 0x4c, 0x38, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x43, 0x6f, 0x6e, 0x76, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x21, 0x4c,
	0x38, 0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x43, 0x4f, 0x4e, 0x56, 0x4f, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x20, 0x0a, 0x1c, 0x4c, 0x38, 0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x43,
	0x4f, 0x4e, 0x56, 0x4f, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x43, 0x54, 0x49,
	0x56, 0x45, 0x10, 0x01, 0x12, 0x22, 0x0a, 0x1e, 0x4c, 0x38, 0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54,
	0x5f, 0x43, 0x4f, 0x4e, 0x56, 0x4f, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x52,
	0x43, 0x48, 0x49, 0x56, 0x45, 0x44, 0x10, 0x02, 0x2a, 0xdd, 0x01, 0x0a, 0x15, 0x4c, 0x38, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x12, 0x28, 0x0a, 0x24, 0x4c, 0x38, 0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x50,
	0x52, 0x4f, 0x4d, 0x50, 0x54, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x24, 0x0a, 0x20,
	0x4c, 0x38, 0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x50, 0x52, 0x4f, 0x4d, 0x50, 0x54, 0x5f,
	0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x47, 0x45, 0x4e, 0x45, 0x52, 0x41, 0x4c,
	0x10, 0x01, 0x12, 0x26, 0x0a, 0x22, 0x4c, 0x38, 0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x50,
	0x52, 0x4f, 0x4d, 0x50, 0x54, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x52,
	0x45, 0x50, 0x4f, 0x52, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x25, 0x0a, 0x21, 0x4c, 0x38,
	0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x50, 0x52, 0x4f, 0x4d, 0x50, 0x54, 0x5f, 0x43, 0x41,
	0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x57, 0x4f, 0x52, 0x4b, 0x46, 0x4c, 0x4f, 0x57, 0x10,
	0x03, 0x12, 0x25, 0x0a, 0x21, 0x4c, 0x38, 0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x50, 0x52,
	0x4f, 0x4d, 0x50, 0x54, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x41, 0x4e,
	0x41, 0x4c, 0x59, 0x53, 0x49, 0x53, 0x10, 0x04, 0x2a, 0x85, 0x01, 0x0a, 0x13, 0x4c, 0x38, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x26, 0x0a, 0x22, 0x4c, 0x38, 0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x50, 0x52, 0x4f,
	0x4d, 0x50, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x21, 0x0a, 0x1d, 0x4c, 0x38, 0x5f, 0x41,
	0x47, 0x45, 0x4e, 0x54, 0x5f, 0x50, 0x52, 0x4f, 0x4d, 0x50, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x23, 0x0a, 0x1f, 0x4c,
	0x38, 0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x50, 0x52, 0x4f, 0x4d, 0x50, 0x54, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x49, 0x4e, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x02,
	0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x6c, 0x38, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_l8agent_proto_rawDescOnce sync.Once
	file_l8agent_proto_rawDescData = file_l8agent_proto_rawDesc
)

func file_l8agent_proto_rawDescGZIP() []byte {
	file_l8agent_proto_rawDescOnce.Do(func() {
		file_l8agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_l8agent_proto_rawDescData)
	})
	return file_l8agent_proto_rawDescData
}

var file_l8agent_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_l8agent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_l8agent_proto_goTypes = []interface{}{
	(L8AgentConvoStatus)(0),             // 0: l8agent.L8AgentConvoStatus
	(L8AgentPromptCategory)(0),          // 1: l8agent.L8AgentPromptCategory
	(L8AgentPromptStatus)(0),            // 2: l8agent.L8AgentPromptStatus
	(*L8AgentConversation)(nil),         // 3: l8agent.L8AgentConversation
	(*L8AgentConversationList)(nil),     // 4: l8agent.L8AgentConversationList
	(*L8AgentChatMessage)(nil),          // 5: l8agent.L8AgentChatMessage
	(*L8AgentChatMessageList)(nil),      // 6: l8agent.L8AgentChatMessageList
	(*L8AgentChatConversation)(nil),     // 7: l8agent.L8AgentChatConversation
	(*L8AgentChatConversationList)(nil), // 8: l8agent.L8AgentChatConversationList
	(*L8AgentPrompt)(nil),               // 9: l8agent.L8AgentPrompt
	(*L8AgentPromptList)(nil),           // 10: l8agent.L8AgentPromptList
	(*l8api.L8MetaData)(nil),            // 11: l8api.L8MetaData
}
var file_l8agent_proto_depIdxs = []int32{
	3,  // 0: l8agent.L8AgentConversationList.list:type_name -> l8agent.L8AgentConversation
	11, // 1: l8agent.L8AgentConversationList.metadata:type_name -> l8api.L8MetaData
	5,  // 2: l8agent.L8AgentChatMessageList.list:type_name -> l8agent.L8AgentChatMessage
	11, // 3: l8agent.L8AgentChatMessageList.metadata:type_name -> l8api.L8MetaData
	5,  // 4: l8agent.L8AgentChatConversation.messages:type_name -> l8agent.L8AgentChatMessage
	7,  // 5: l8agent.L8AgentChatConversationList.list:type_name -> l8agent.L8AgentChatConversation
	11, // 6: l8agent.L8AgentChatConversationList.metadata:type_name -> l8api.L8MetaData
	9,  // 7: l8agent.L8AgentPromptList.list:type_name -> l8agent.L8AgentPrompt
	11, // 8: l8agent.L8AgentPromptList.metadata:type_name -> l8api.L8MetaData
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_l8agent_proto_init() }
func file_l8agent_proto_init() {
	if File_l8agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_l8agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8AgentConversation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8AgentConversationList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8agent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8AgentChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8agent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8AgentChatMessageList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8agent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8AgentChatConversation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8agent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8AgentChatConversationList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8agent_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8AgentPrompt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8agent_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8AgentPromptList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_l8agent_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_l8agent_proto_goTypes,
		DependencyIndexes: file_l8agent_proto_depIdxs,
		EnumInfos:         file_l8agent_proto_enumTypes,
		MessageInfos:      file_l8agent_proto_msgTypes,
	}.Build()
	File_l8agent_proto = out.File
	file_l8agent_proto_rawDesc = nil
	file_l8agent_proto_goTypes = nil
	file_l8agent_proto_depIdxs = nil
}
