// © 2025 Sharon Aicler (saichler@gmail.com)
//
// Layer 8 Ecosystem is licensed under the Apache License, Version 2.0.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// l8agent.proto defines the types for the Layer 8 AI Agent shared library.
// These types are used by all Layer 8 projects that integrate the AI agent.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: l8agent.proto

package l8agent

import (
	l8api "github.com/saichler/l8types/go/types/l8api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type L8AgentConvoStatus int32

const (
	L8AgentConvoStatus_L8_AGENT_CONVO_STATUS_UNSPECIFIED L8AgentConvoStatus = 0
	L8AgentConvoStatus_L8_AGENT_CONVO_STATUS_ACTIVE      L8AgentConvoStatus = 1
	L8AgentConvoStatus_L8_AGENT_CONVO_STATUS_ARCHIVED    L8AgentConvoStatus = 2
)

// Enum value maps for L8AgentConvoStatus.
var (
	L8AgentConvoStatus_name = map[int32]string{
		0: "L8_AGENT_CONVO_STATUS_UNSPECIFIED",
		1: "L8_AGENT_CONVO_STATUS_ACTIVE",
		2: "L8_AGENT_CONVO_STATUS_ARCHIVED",
	}
	L8AgentConvoStatus_value = map[string]int32{
		"L8_AGENT_CONVO_STATUS_UNSPECIFIED": 0,
		"L8_AGENT_CONVO_STATUS_ACTIVE":      1,
		"L8_AGENT_CONVO_STATUS_ARCHIVED":    2,
	}
)

func (x L8AgentConvoStatus) Enum() *L8AgentConvoStatus {
	p := new(L8AgentConvoStatus)
	*p = x
	return p
}

func (x L8AgentConvoStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (L8AgentConvoStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_l8agent_proto_enumTypes[0].Descriptor()
}

func (L8AgentConvoStatus) Type() protoreflect.EnumType {
	return &file_l8agent_proto_enumTypes[0]
}

func (x L8AgentConvoStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use L8AgentConvoStatus.Descriptor instead.
func (L8AgentConvoStatus) EnumDescriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{0}
}

type L8AgentMessageRole int32

const (
	L8AgentMessageRole_L8_AGENT_MESSAGE_ROLE_UNSPECIFIED L8AgentMessageRole = 0
	L8AgentMessageRole_L8_AGENT_MESSAGE_ROLE_USER        L8AgentMessageRole = 1
	L8AgentMessageRole_L8_AGENT_MESSAGE_ROLE_ASSISTANT   L8AgentMessageRole = 2
	L8AgentMessageRole_L8_AGENT_MESSAGE_ROLE_SYSTEM      L8AgentMessageRole = 3
)

// Enum value maps for L8AgentMessageRole.
var (
	L8AgentMessageRole_name = map[int32]string{
		0: "L8_AGENT_MESSAGE_ROLE_UNSPECIFIED",
		1: "L8_AGENT_MESSAGE_ROLE_USER",
		2: "L8_AGENT_MESSAGE_ROLE_ASSISTANT",
		3: "L8_AGENT_MESSAGE_ROLE_SYSTEM",
	}
	L8AgentMessageRole_value = map[string]int32{
		"L8_AGENT_MESSAGE_ROLE_UNSPECIFIED": 0,
		"L8_AGENT_MESSAGE_ROLE_USER":        1,
		"L8_AGENT_MESSAGE_ROLE_ASSISTANT":   2,
		"L8_AGENT_MESSAGE_ROLE_SYSTEM":      3,
	}
)

func (x L8AgentMessageRole) Enum() *L8AgentMessageRole {
	p := new(L8AgentMessageRole)
	*p = x
	return p
}

func (x L8AgentMessageRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (L8AgentMessageRole) Descriptor() protoreflect.EnumDescriptor {
	return file_l8agent_proto_enumTypes[1].Descriptor()
}

func (L8AgentMessageRole) Type() protoreflect.EnumType {
	return &file_l8agent_proto_enumTypes[1]
}

func (x L8AgentMessageRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use L8AgentMessageRole.Descriptor instead.
func (L8AgentMessageRole) EnumDescriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{1}
}

type L8AgentPromptCategory int32

const (
	L8AgentPromptCategory_L8_AGENT_PROMPT_CATEGORY_UNSPECIFIED L8AgentPromptCategory = 0
	L8AgentPromptCategory_L8_AGENT_PROMPT_CATEGORY_GENERAL     L8AgentPromptCategory = 1
	L8AgentPromptCategory_L8_AGENT_PROMPT_CATEGORY_REPORTING   L8AgentPromptCategory = 2
	L8AgentPromptCategory_L8_AGENT_PROMPT_CATEGORY_WORKFLOW    L8AgentPromptCategory = 3
	L8AgentPromptCategory_L8_AGENT_PROMPT_CATEGORY_ANALYSIS    L8AgentPromptCategory = 4
)

// Enum value maps for L8AgentPromptCategory.
var (
	L8AgentPromptCategory_name = map[int32]string{
		0: "L8_AGENT_PROMPT_CATEGORY_UNSPECIFIED",
		1: "L8_AGENT_PROMPT_CATEGORY_GENERAL",
		2: "L8_AGENT_PROMPT_CATEGORY_REPORTING",
		3: "L8_AGENT_PROMPT_CATEGORY_WORKFLOW",
		4: "L8_AGENT_PROMPT_CATEGORY_ANALYSIS",
	}
	L8AgentPromptCategory_value = map[string]int32{
		"L8_AGENT_PROMPT_CATEGORY_UNSPECIFIED": 0,
		"L8_AGENT_PROMPT_CATEGORY_GENERAL":     1,
		"L8_AGENT_PROMPT_CATEGORY_REPORTING":   2,
		"L8_AGENT_PROMPT_CATEGORY_WORKFLOW":    3,
		"L8_AGENT_PROMPT_CATEGORY_ANALYSIS":    4,
	}
)

func (x L8AgentPromptCategory) Enum() *L8AgentPromptCategory {
	p := new(L8AgentPromptCategory)
	*p = x
	return p
}

func (x L8AgentPromptCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (L8AgentPromptCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_l8agent_proto_enumTypes[2].Descriptor()
}

func (L8AgentPromptCategory) Type() protoreflect.EnumType {
	return &file_l8agent_proto_enumTypes[2]
}

func (x L8AgentPromptCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use L8AgentPromptCategory.Descriptor instead.
func (L8AgentPromptCategory) EnumDescriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{2}
}

type L8AgentPromptStatus int32

const (
	L8AgentPromptStatus_L8_AGENT_PROMPT_STATUS_UNSPECIFIED L8AgentPromptStatus = 0
	L8AgentPromptStatus_L8_AGENT_PROMPT_STATUS_ACTIVE      L8AgentPromptStatus = 1
	L8AgentPromptStatus_L8_AGENT_PROMPT_STATUS_INACTIVE    L8AgentPromptStatus = 2
)

// Enum value maps for L8AgentPromptStatus.
var (
	L8AgentPromptStatus_name = map[int32]string{
		0: "L8_AGENT_PROMPT_STATUS_UNSPECIFIED",
		1: "L8_AGENT_PROMPT_STATUS_ACTIVE",
		2: "L8_AGENT_PROMPT_STATUS_INACTIVE",
	}
	L8AgentPromptStatus_value = map[string]int32{
		"L8_AGENT_PROMPT_STATUS_UNSPECIFIED": 0,
		"L8_AGENT_PROMPT_STATUS_ACTIVE":      1,
		"L8_AGENT_PROMPT_STATUS_INACTIVE":    2,
	}
)

func (x L8AgentPromptStatus) Enum() *L8AgentPromptStatus {
	p := new(L8AgentPromptStatus)
	*p = x
	return p
}

func (x L8AgentPromptStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (L8AgentPromptStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_l8agent_proto_enumTypes[3].Descriptor()
}

func (L8AgentPromptStatus) Type() protoreflect.EnumType {
	return &file_l8agent_proto_enumTypes[3]
}

func (x L8AgentPromptStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use L8AgentPromptStatus.Descriptor instead.
func (L8AgentPromptStatus) EnumDescriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{3}
}

// L8AgentConversation - Prime Object
// Passes Prime Object test: independent lifecycle, queried directly,
// meaningful on its own (conversation history)
type L8AgentConversation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string            `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string            `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title          string            `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Status         int32             `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`    // L8AgentConvoStatus enum
	Messages       []*L8AgentMessage `protobuf:"bytes,5,rep,name=messages,proto3" json:"messages,omitempty"` // Embedded child - not independent
	CreatedAt      int64             `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64             `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *L8AgentConversation) Reset() {
	*x = L8AgentConversation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8AgentConversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8AgentConversation) ProtoMessage() {}

func (x *L8AgentConversation) ProtoReflect() protoreflect.Message {
	mi := &file_l8agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8AgentConversation.ProtoReflect.Descriptor instead.
func (*L8AgentConversation) Descriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{0}
}

func (x *L8AgentConversation) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *L8AgentConversation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *L8AgentConversation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *L8AgentConversation) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *L8AgentConversation) GetMessages() []*L8AgentMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *L8AgentConversation) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *L8AgentConversation) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// L8AgentMessage - Embedded child (NOT a Prime Object)
// Fails Prime Object test: meaningless without a conversation,
// always created/viewed within conversation context
type L8AgentMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId   string               `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Role        int32                `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"` // L8AgentMessageRole enum
	Content     string               `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ToolCalls   []*L8AgentToolCall   `protobuf:"bytes,4,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	ToolResults []*L8AgentToolResult `protobuf:"bytes,5,rep,name=tool_results,json=toolResults,proto3" json:"tool_results,omitempty"`
	Timestamp   int64                `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TokenCount  int32                `protobuf:"varint,7,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
}

func (x *L8AgentMessage) Reset() {
	*x = L8AgentMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8AgentMessage) ProtoMessage() {}

func (x *L8AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_l8agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8AgentMessage.ProtoReflect.Descriptor instead.
func (*L8AgentMessage) Descriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{1}
}

func (x *L8AgentMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *L8AgentMessage) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *L8AgentMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *L8AgentMessage) GetToolCalls() []*L8AgentToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *L8AgentMessage) GetToolResults() []*L8AgentToolResult {
	if x != nil {
		return x.ToolResults
	}
	return nil
}

func (x *L8AgentMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *L8AgentMessage) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

// L8AgentToolCall - Embedded child within L8AgentMessage
type L8AgentToolCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToolCallId string `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolName   string `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolInput  string `protobuf:"bytes,3,opt,name=tool_input,json=toolInput,proto3" json:"tool_input,omitempty"` // JSON string
}

func (x *L8AgentToolCall) Reset() {
	*x = L8AgentToolCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8AgentToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8AgentToolCall) ProtoMessage() {}

func (x *L8AgentToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_l8agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8AgentToolCall.ProtoReflect.Descriptor instead.
func (*L8AgentToolCall) Descriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{2}
}

func (x *L8AgentToolCall) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *L8AgentToolCall) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *L8AgentToolCall) GetToolInput() string {
	if x != nil {
		return x.ToolInput
	}
	return ""
}

// L8AgentToolResult - Embedded child within L8AgentMessage
type L8AgentToolResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToolCallId string `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	Result     string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"` // JSON string
	IsError    bool   `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
}

func (x *L8AgentToolResult) Reset() {
	*x = L8AgentToolResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8AgentToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8AgentToolResult) ProtoMessage() {}

func (x *L8AgentToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_l8agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8AgentToolResult.ProtoReflect.Descriptor instead.
func (*L8AgentToolResult) Descriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{3}
}

func (x *L8AgentToolResult) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *L8AgentToolResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *L8AgentToolResult) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

// L8AgentPrompt - Prime Object
// Passes Prime Object test: independent lifecycle, queried across all users,
// reusable templates not tied to a single conversation
type L8AgentPrompt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PromptId       string   `protobuf:"bytes,1,opt,name=prompt_id,json=promptId,proto3" json:"prompt_id,omitempty"`
	Name           string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SystemPrompt   string   `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`       // The prompt template text
	Category       int32    `protobuf:"varint,5,opt,name=category,proto3" json:"category,omitempty"`                                  // L8AgentPromptCategory enum
	Status         int32    `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`                                      // L8AgentPromptStatus enum
	AllowedModules []string `protobuf:"bytes,7,rep,name=allowed_modules,json=allowedModules,proto3" json:"allowed_modules,omitempty"` // Module keys the prompt can access
	CreatedBy      string   `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
}

func (x *L8AgentPrompt) Reset() {
	*x = L8AgentPrompt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8agent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8AgentPrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8AgentPrompt) ProtoMessage() {}

func (x *L8AgentPrompt) ProtoReflect() protoreflect.Message {
	mi := &file_l8agent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8AgentPrompt.ProtoReflect.Descriptor instead.
func (*L8AgentPrompt) Descriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{4}
}

func (x *L8AgentPrompt) GetPromptId() string {
	if x != nil {
		return x.PromptId
	}
	return ""
}

func (x *L8AgentPrompt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *L8AgentPrompt) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *L8AgentPrompt) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *L8AgentPrompt) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *L8AgentPrompt) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *L8AgentPrompt) GetAllowedModules() []string {
	if x != nil {
		return x.AllowedModules
	}
	return nil
}

func (x *L8AgentPrompt) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

// L8AgentChatRequest - NOT a Prime Object, not stored
// Transient request payload for the chat endpoint
type L8AgentChatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string   `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // Empty = new conversation
	Message        string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                     // User's message
	PromptId       string   `protobuf:"bytes,3,opt,name=prompt_id,json=promptId,proto3" json:"prompt_id,omitempty"`                   // Optional: use a specific prompt template
	AllowedModules []string `protobuf:"bytes,4,rep,name=allowed_modules,json=allowedModules,proto3" json:"allowed_modules,omitempty"` // Optional: restrict modules for this request
}

func (x *L8AgentChatRequest) Reset() {
	*x = L8AgentChatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8agent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8AgentChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8AgentChatRequest) ProtoMessage() {}

func (x *L8AgentChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_l8agent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8AgentChatRequest.ProtoReflect.Descriptor instead.
func (*L8AgentChatRequest) Descriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{5}
}

func (x *L8AgentChatRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *L8AgentChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *L8AgentChatRequest) GetPromptId() string {
	if x != nil {
		return x.PromptId
	}
	return ""
}

func (x *L8AgentChatRequest) GetAllowedModules() []string {
	if x != nil {
		return x.AllowedModules
	}
	return nil
}

// L8AgentChatResponse - NOT a Prime Object, not stored
// Transient response payload
type L8AgentChatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string               `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Response       string               `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"` // Agent's text response
	DataResults    []*L8AgentDataResult `protobuf:"bytes,3,rep,name=data_results,json=dataResults,proto3" json:"data_results,omitempty"`
	ToolCallsMade  int32                `protobuf:"varint,4,opt,name=tool_calls_made,json=toolCallsMade,proto3" json:"tool_calls_made,omitempty"`
	TotalTokens    int32                `protobuf:"varint,5,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
}

func (x *L8AgentChatResponse) Reset() {
	*x = L8AgentChatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8agent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8AgentChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8AgentChatResponse) ProtoMessage() {}

func (x *L8AgentChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_l8agent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8AgentChatResponse.ProtoReflect.Descriptor instead.
func (*L8AgentChatResponse) Descriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{6}
}

func (x *L8AgentChatResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *L8AgentChatResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *L8AgentChatResponse) GetDataResults() []*L8AgentDataResult {
	if x != nil {
		return x.DataResults
	}
	return nil
}

func (x *L8AgentChatResponse) GetToolCallsMade() int32 {
	if x != nil {
		return x.ToolCallsMade
	}
	return 0
}

func (x *L8AgentChatResponse) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

// L8AgentDataResult - Embedded in L8AgentChatResponse
type L8AgentDataResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModelName  string `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Query      string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	DataJson   string `protobuf:"bytes,3,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"` // JSON array of results
	TotalCount int32  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *L8AgentDataResult) Reset() {
	*x = L8AgentDataResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8agent_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8AgentDataResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8AgentDataResult) ProtoMessage() {}

func (x *L8AgentDataResult) ProtoReflect() protoreflect.Message {
	mi := &file_l8agent_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8AgentDataResult.ProtoReflect.Descriptor instead.
func (*L8AgentDataResult) Descriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{7}
}

func (x *L8AgentDataResult) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *L8AgentDataResult) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *L8AgentDataResult) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

func (x *L8AgentDataResult) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// List types
type L8AgentConversationList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*L8AgentConversation `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata *l8api.L8MetaData      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *L8AgentConversationList) Reset() {
	*x = L8AgentConversationList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8agent_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8AgentConversationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8AgentConversationList) ProtoMessage() {}

func (x *L8AgentConversationList) ProtoReflect() protoreflect.Message {
	mi := &file_l8agent_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8AgentConversationList.ProtoReflect.Descriptor instead.
func (*L8AgentConversationList) Descriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{8}
}

func (x *L8AgentConversationList) GetList() []*L8AgentConversation {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *L8AgentConversationList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type L8AgentPromptList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*L8AgentPrompt  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata *l8api.L8MetaData `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *L8AgentPromptList) Reset() {
	*x = L8AgentPromptList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8agent_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8AgentPromptList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8AgentPromptList) ProtoMessage() {}

func (x *L8AgentPromptList) ProtoReflect() protoreflect.Message {
	mi := &file_l8agent_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8AgentPromptList.ProtoReflect.Descriptor instead.
func (*L8AgentPromptList) Descriptor() ([]byte, []int) {
	return file_l8agent_proto_rawDescGZIP(), []int{9}
}

func (x *L8AgentPromptList) GetList() []*L8AgentPrompt {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *L8AgentPromptList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_l8agent_proto protoreflect.FileDescriptor

var file_l8agent_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6c, 0x38, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6c, 0x38, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x1a, 0x0b, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf8, 0x01, 0x0a, 0x13, 0x4c, 0x38, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a,
	0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x33, 0x0a,
	0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x6c, 0x38, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x38, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x22, 0x94, 0x02, 0x0a, 0x0e, 0x4c, 0x38, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x37, 0x0a, 0x0a, 0x74, 0x6f, 0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x38, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4c,
	0x38, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6f, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x09,
	0x74, 0x6f, 0x6f, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x73, 0x12, 0x3d, 0x0a, 0x0c, 0x74, 0x6f, 0x6f,
	0x6c, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x6c, 0x38, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x38, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x54, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0b, 0x74, 0x6f, 0x6f,
	0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x6f, 0x0a, 0x0f, 0x4c, 0x38, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x54, 0x6f, 0x6f, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x20, 0x0a, 0x0c, 0x74, 0x6f,
	0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x74, 0x6f, 0x6f, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x74, 0x6f, 0x6f, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x74, 0x6f, 0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x6f,
	0x6c, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74,
	0x6f, 0x6f, 0x6c, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x68, 0x0a, 0x11, 0x4c, 0x38, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x20, 0x0a,
	0x0c, 0x74, 0x6f, 0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x6f, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x83, 0x02, 0x0a, 0x0d, 0x4c, 0x38, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x50, 0x72,
	0x6f, 0x6d, 0x70, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x27, 0x0a, 0x0f, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x64, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x22, 0x9d, 0x01, 0x0a, 0x12, 0x4c, 0x38, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72,
	0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x49, 0x64, 0x12,
	0x27, 0x0a, 0x0f, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65,
	0x64, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x22, 0xe4, 0x01, 0x0a, 0x13, 0x4c, 0x38, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65,
	0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x38,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x38, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x74, 0x6f, 0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x6c,
	0x6c, 0x73, 0x5f, 0x6d, 0x61, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x74,
	0x6f, 0x6f, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x73, 0x4d, 0x61, 0x64, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x22,
	0x86, 0x01, 0x0a, 0x11, 0x4c, 0x38, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64,
	0x61, 0x74, 0x61, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x7a, 0x0a, 0x17, 0x4c, 0x38, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x6c, 0x38, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x38, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e,
	0x4c, 0x38, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x6e, 0x0a, 0x11, 0x4c, 0x38, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x50,
	0x72, 0x6f, 0x6d, 0x70, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x38, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x4c, 0x38, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x52,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e,
	0x4c, 0x38, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x2a, 0x81, 0x01, 0x0a, 0x12, 0x4c, 0x38, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x43, 0x6f, 0x6e, 0x76, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x21, 0x4c,
	0x38, 0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x43, 0x4f, 0x4e, 0x56, 0x4f, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x20, 0x0a, 0x1c, 0x4c, 0x38, 0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x43,
	0x4f, 0x4e, 0x56, 0x4f, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x43, 0x54, 0x49,
	0x56, 0x45, 0x10, 0x01, 0x12, 0x22, 0x0a, 0x1e, 0x4c, 0x38, 0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54,
	0x5f, 0x43, 0x4f, 0x4e, 0x56, 0x4f, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x52,
	0x43, 0x48, 0x49, 0x56, 0x45, 0x44, 0x10, 0x02, 0x2a, 0xa2, 0x01, 0x0a, 0x12, 0x4c, 0x38, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x12,
	0x25, 0x0a, 0x21, 0x4c, 0x38, 0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x4d, 0x45, 0x53, 0x53,
	0x41, 0x47, 0x45, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x4c, 0x38, 0x5f, 0x41, 0x47, 0x45,
	0x4e, 0x54, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x5f,
	0x55, 0x53, 0x45, 0x52, 0x10, 0x01, 0x12, 0x23, 0x0a, 0x1f, 0x4c, 0x38, 0x5f, 0x41, 0x47, 0x45,
	0x4e, 0x54, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x5f,
	0x41, 0x53, 0x53, 0x49, 0x53, 0x54, 0x41, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x20, 0x0a, 0x1c, 0x4c,
	0x38, 0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f,
	0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x10, 0x03, 0x2a, 0xdd, 0x01,
	0x0a, 0x15, 0x4c, 0x38, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x28, 0x0a, 0x24, 0x4c, 0x38, 0x5f, 0x41, 0x47,
	0x45, 0x4e, 0x54, 0x5f, 0x50, 0x52, 0x4f, 0x4d, 0x50, 0x54, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47,
	0x4f, 0x52, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x24, 0x0a, 0x20, 0x4c, 0x38, 0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x50, 0x52,
	0x4f, 0x4d, 0x50, 0x54, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x47, 0x45,
	0x4e, 0x45, 0x52, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x26, 0x0a, 0x22, 0x4c, 0x38, 0x5f, 0x41, 0x47,
	0x45, 0x4e, 0x54, 0x5f, 0x50, 0x52, 0x4f, 0x4d, 0x50, 0x54, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47,
	0x4f, 0x52, 0x59, 0x5f, 0x52, 0x45, 0x50, 0x4f, 0x52, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12,
	0x25, 0x0a, 0x21, 0x4c, 0x38, 0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x50, 0x52, 0x4f, 0x4d,
	0x50, 0x54, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x57, 0x4f, 0x52, 0x4b,
	0x46, 0x4c, 0x4f, 0x57, 0x10, 0x03, 0x12, 0x25, 0x0a, 0x21, 0x4c, 0x38, 0x5f, 0x41, 0x47, 0x45,
	0x4e, 0x54, 0x5f, 0x50, 0x52, 0x4f, 0x4d, 0x50, 0x54, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f,
	0x52, 0x59, 0x5f, 0x41, 0x4e, 0x41, 0x4c, 0x59, 0x53, 0x49, 0x53, 0x10, 0x04, 0x2a, 0x85, 0x01,
	0x0a, 0x13, 0x4c, 0x38, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x26, 0x0a, 0x22, 0x4c, 0x38, 0x5f, 0x41, 0x47, 0x45, 0x4e,
	0x54, 0x5f, 0x50, 0x52, 0x4f, 0x4d, 0x50, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x21, 0x0a,
	0x1d, 0x4c, 0x38, 0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x50, 0x52, 0x4f, 0x4d, 0x50, 0x54,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01,
	0x12, 0x23, 0x0a, 0x1f, 0x4c, 0x38, 0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x50, 0x52, 0x4f,
	0x4d, 0x50, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x49, 0x4e, 0x41, 0x43, 0x54,
	0x49, 0x56, 0x45, 0x10, 0x02, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2f, 0x6c, 0x38, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_l8agent_proto_rawDescOnce sync.Once
	file_l8agent_proto_rawDescData = file_l8agent_proto_rawDesc
)

func file_l8agent_proto_rawDescGZIP() []byte {
	file_l8agent_proto_rawDescOnce.Do(func() {
		file_l8agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_l8agent_proto_rawDescData)
	})
	return file_l8agent_proto_rawDescData
}

var file_l8agent_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_l8agent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_l8agent_proto_goTypes = []interface{}{
	(L8AgentConvoStatus)(0),         // 0: l8agent.L8AgentConvoStatus
	(L8AgentMessageRole)(0),         // 1: l8agent.L8AgentMessageRole
	(L8AgentPromptCategory)(0),      // 2: l8agent.L8AgentPromptCategory
	(L8AgentPromptStatus)(0),        // 3: l8agent.L8AgentPromptStatus
	(*L8AgentConversation)(nil),     // 4: l8agent.L8AgentConversation
	(*L8AgentMessage)(nil),          // 5: l8agent.L8AgentMessage
	(*L8AgentToolCall)(nil),         // 6: l8agent.L8AgentToolCall
	(*L8AgentToolResult)(nil),       // 7: l8agent.L8AgentToolResult
	(*L8AgentPrompt)(nil),           // 8: l8agent.L8AgentPrompt
	(*L8AgentChatRequest)(nil),      // 9: l8agent.L8AgentChatRequest
	(*L8AgentChatResponse)(nil),     // 10: l8agent.L8AgentChatResponse
	(*L8AgentDataResult)(nil),       // 11: l8agent.L8AgentDataResult
	(*L8AgentConversationList)(nil), // 12: l8agent.L8AgentConversationList
	(*L8AgentPromptList)(nil),       // 13: l8agent.L8AgentPromptList
	(*l8api.L8MetaData)(nil),        // 14: l8api.L8MetaData
}
var file_l8agent_proto_depIdxs = []int32{
	5,  // 0: l8agent.L8AgentConversation.messages:type_name -> l8agent.L8AgentMessage
	6,  // 1: l8agent.L8AgentMessage.tool_calls:type_name -> l8agent.L8AgentToolCall
	7,  // 2: l8agent.L8AgentMessage.tool_results:type_name -> l8agent.L8AgentToolResult
	11, // 3: l8agent.L8AgentChatResponse.data_results:type_name -> l8agent.L8AgentDataResult
	4,  // 4: l8agent.L8AgentConversationList.list:type_name -> l8agent.L8AgentConversation
	14, // 5: l8agent.L8AgentConversationList.metadata:type_name -> l8api.L8MetaData
	8,  // 6: l8agent.L8AgentPromptList.list:type_name -> l8agent.L8AgentPrompt
	14, // 7: l8agent.L8AgentPromptList.metadata:type_name -> l8api.L8MetaData
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_l8agent_proto_init() }
func file_l8agent_proto_init() {
	if File_l8agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_l8agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8AgentConversation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8AgentMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8agent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8AgentToolCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8agent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8AgentToolResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8agent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8AgentPrompt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8agent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8AgentChatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8agent_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8AgentChatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8agent_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8AgentDataResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8agent_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8AgentConversationList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8agent_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8AgentPromptList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_l8agent_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_l8agent_proto_goTypes,
		DependencyIndexes: file_l8agent_proto_depIdxs,
		EnumInfos:         file_l8agent_proto_enumTypes,
		MessageInfos:      file_l8agent_proto_msgTypes,
	}.Build()
	File_l8agent_proto = out.File
	file_l8agent_proto_rawDesc = nil
	file_l8agent_proto_goTypes = nil
	file_l8agent_proto_depIdxs = nil
}
